name: Update Python & Launcher Cache

on:
  push:
    branches:
      - ublue-linux
      - main
    paths:
      - 'requirements.txt'
      - 'data/app/launcher/**'
  workflow_dispatch: # 手動実行用

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  update-cache:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python Embeddable
        uses: ./.github/actions/setup-python-embed

      - name: Build Go Launcher
        uses: ./.github/actions/build-go-launcher


